### ISSUE TITLE
use the last available image

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#101]
This would allow us to use the functionality of gitlab CI which can limit job triggers to only when specific paths change. E.g. we could enable such a `.gitlab-ci.yml`:

```
image_build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script:
    - CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - docker pull renku/singleuser:latest
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7
  only: 
    changes:
      - Dockerfile
      - requirements.txt 
      - envs/*
  tags:
    - image-build
```
