### ISSUE TITLE
Renku 2.0 sessions cannot start when a project has zero repositories and one or more data sources

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-notebooks#1891]
The issue stems from the inclusion of the following patch:

```yaml
 - patch:
    - op: add
      path: /statefulset/spec/template/spec/initContainers/2/env/-
      value:
        name: GIT_CLONE_STORAGE_MOUNTS_0
        value: /home/jovyan/work/external_storage/giab
    type: application/json-patch+json
```
