### ISSUE TITLE
Enable S3/NFS mounts in interactive sessions

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#468]
Currently, all data that users want to access when working in interactive environments has to be downloaded into the environment, either during environment launch or manually by the user later on. This approach is not very user friendly and consumes unnecessary amounts of disk space and bandwitdh in scenarios where only a small subset of all the data contained in a dataset (or data folder, etc) effectively has to be accessed. 

One way to improve this would be to allow users to FUSE-mount a volume/s3-bucket into their environments. See [this thread on discourse](https://renku.discourse.group/t/run-environment-with-fuse-module-to-mount-external-data/204) for an example use case.

Letting users simply handle this themselves is unfortunately not an option because of the escalated privileges a container (at least until now, see for example [this issue](https://github.com/docker/for-linux/issues/321)) needs in order to mount volumes. Instead, we could do the mount in a different container and make the mounted volume available to the user session. This would have to be realised through some dedicated component deployed as `deamonSet` on each node or as init- or sidecar container running alongside the jupyterlab container in the user session pod.

Open questions that have to be addressed before we can move forward on this issue include:
- What are the security implications of running privileged and unprivileged containers in the same pod? Can a privilege escalation be prevented? Do pod security policies help here? 
- What would a `deamonSet` based solution look like? Would a volume be mounted on every node or only on the node running the user pod? How could we reliably manage paths of the mounted volumes on the nodes?
- What would the UX be around this?
- How do we reliably handle the users credentials?

**Comment by rokroskar** [comment]
Update - this might be a feasible way forward without having to manage the mounting ourselves: https://ibm.github.io/dataset-lifecycle-framework/

**Comment by olevski** [comment]
I could not get this to work on the dev cluster. But I only tried once and was too afraid to break things for other people so I stopped.

However, I deployed the terraform-renku config that is at commit `5bf0d5fcf33db9f48e4a52ce17df24ea4d234898` on main. Then I installed the https://ibm.github.io/dataset-lifecycle-framework/ library by following the instructions (it is a one line command that applies a manifest). They still do not have a helm chart.

After creating the crds that com from the DLF library I tested:
- creating and mounting a dataset in read-only mode with gcs storage
- creating and mounting a dataset in read-write mode with openstack object storage
- creating and mounting a dataset in read-write mode with gcs storage

All of the above scenarios work. I could see the changes reflected on the openstack page for object storage in read-write mode. I could also mount the same dataset to 2 pods at the same time. And changing things from one pod was reflected in another. I am not sure what happens when you try to edit the same file from two different places at the same time. It is probably not nice.

The only problem is that the pvc and pv created from the s3 bucket is always ~9000 gb large. I posted a question on the github page for DLF if we can control this (https://github.com/IBM/dataset-lifecycle-framework/issues/87)

These tests included only simple pods that ran busybox. My next step is to deploy renku in my cluster and test it out with renku. However I do not see a reason why the user pods would not work for this if regular pods did work. 

So my next step is to deploy renku and test this out in a user pod.

The way that a DLF dataset k8s resources is created and mounted is very easy and would work with the renku spawner. We would require the user to provide s3 secret and acces keys, s3 api endpoint as well as bucket names that should be mounted.

**Comment by olevski** [comment]
For reference these are my manifests for creating the dataset crds which then create a pvc with the s3 bucket data:
```yaml
# source https://github.com/IBM/dataset-lifecycle-framework/tree/master/examples/templates
---
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset-openstack
  namespace: tasko
spec:
  local:
    type: "COS"
    secret-name: "s3-dataset-secret-openstack" #see s3-secrets.yaml for an example
    secret-namespace: "tasko" #optional if the secret is in the same ns as dataset
    endpoint: "https://os.zhdk.cloud.switch.ch"
    bucket: "dlf-dataset-test-1"
    readonly: "false" # default is false
    region: "" #it can be empty
---
kind: Namespace
apiVersion: v1
metadata:
  name: tasko
---
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset-gcs
  namespace: tasko
spec:
  local:
    type: "COS"
    secret-name: "s3-dataset-secret-gcs" #see s3-secrets.yaml for an example
    secret-namespace: "tasko" #optional if the secret is in the same ns as dataset
    endpoint: "https://storage.googleapis.com"
    bucket: "tasko-dlf-test-1"
    readonly: "false" # default is false
    region: "europe-west6" #it can be empty
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-dataset-secret-openstack
  namespace: tasko
stringData:
  accessKeyID: "xxxxxxxxxxx"
  secretAccessKey: "xxxxxxxxxxx"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-dataset-secret-gcs
  namespace: tasko
stringData:
  accessKeyID: "xxxxxxxxxxx"
  secretAccessKey: "xxxxxxxxxxx"
```

Then all I have to do is mount the pvcs in any pod I want:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-dataset-pod
spec:
  volumes:
    - name: datasetpvc
      persistentVolumeClaim:
        claimName: example-dataset-openstack
  containers:
    - name: main
      image: busybox
      command:
        - sh
        - -c
      args: 
        - sleep 30000
      volumeMounts:
        - mountPath: "/dataset"
          name: datasetpvc
```
