### ISSUE TITLE
Mount S3 buckets into user sessions by using a privileged sidecar container

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-notebooks#874]
This is possible and it would allow us to not rely on datashim.io. It seems that datashim.io is not actively supported or if it is then the maintainers are not very responsive.

See the following comments for a proof of concept manifest on how this can be done.

Remaining questions that need to be answered:
- how does the API for this look like?
- should we make this part of Amalthea?
- do we allow live patching/changes of an existing session? (this could be possible because the sidecar container can change/add s3 mounts while the session is active)
- is it possible to make this into a fully standalone service (i.e. not have a sidecar per user session)
- is it acceptable to have a sidecar container that runs with elevated privileges?

**Comment by olevski** [comment]
Example manifest:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
spec:
  automountServiceAccountToken: false
  containers:
  - name: s3-mounter
    securityContext:
      runAsGroup: 100
      runAsUser: 1000
      privileged: true
    image: olevski90/s3-mounter:0.0.2
    resources:
      limits:
        memory: 500Mi
        cpu: 500m
      requests:
        memory: 500Mi
        cpu: 500m
    command:
      - "bash"
      - "-c"
    args: 
      - |
        mkdir -p /datasets/giab
        s3fs giab /datasets/giab -o url=http://s3.amazonaws.com -o use_path_request_style -o public_bucket=1
        sleep 9999999999999999999
    volumeMounts:
    - mountPath: /datasets
      name: test-pod-pvc
      mountPropagation: Bidirectional
  - args:
    - jupyter
    - notebook
    image: renku/renkulab-py:3.9-0.10.1
    imagePullPolicy: IfNotPresent
    name: jupyter-server
    resources:
      limits:
        memory: 1G
      requests:
        cpu: 100m
        memory: 1G
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 100
      runAsUser: 1000
    volumeMounts:
    - mountPath: /home/jovyan/work
      name: workspace
    - mountPath: /datasets
      name: test-pod-pvc
      mountPropagation: HostToContainer
    workingDir: /home/jovyan/work/test-project-size-1/
  securityContext:
    fsGroup: 100
  volumes:
  - emptyDir:
      sizeLimit: 1G
    name: workspace
  - name: test-pod-pvc
    emptyDir: {}
```

Mounter s3 image used:
```Dockerfile
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    s3fs \
    && rm -rf /var/lib/apt/lists/* \
    && useradd jovyan \
    && usermod -u 1000 -g 100 jovyan
```
