### ISSUE TITLE
set ephemeral storage limits on pods

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-notebooks#92]
Pod disk storage is turning out to be a problem (not unexpectedly) -- we should allow pods to make a resource request for ephemeral storage.

**Comment by mohammad-sdsc** [comment]
I've tested `request` and `limit` options for the `ephemeral-storage` on `testing-terraform-script` node, a node for that was brought up by @pameladelgado. I've used the following pod description and played with `dd` parameters to go over and under the node's limit.

```
apiVersion: v1
kind: Pod
metadata:
  name: storage-over-limit
  namespace: storage-limit
spec:
  containers:
  - name: storage-over-limit
    image: polinux/stress
    resources:
      requests:
        ephemeral-storage: "1000Mi"
      limits:
        ephemeral-storage: "3Gi"
    command: ["/bin/sh", "-c"]
    args: 
    - dd if=/dev/urandom of=/my-storage/dump bs=1M count=2000 ;
      sleep 1000000000
    volumeMounts:
    - name: my-ephemeral-storage
      mountPath: /my-storage
      readOnly: false
  nodeSelector:
    node-purpose: test-memory
  tolerations:
  - key: "special"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  volumes:
  - name: my-ephemeral-storage
    emptyDir: {}
```

I've observed that:
1. When a pod consumes more space that its `limit` it gets evicted.
2. When a pod consumes more space that its `request` but below its `limit` it can continue working while node has enough storage space.
3. When a node is low on storage space it evicts a pod to make space. It seems that nodes that are consuming more than their `request`, get evicted first.
3. Evicted pods are not restarted.
